name:                HW4
version:             0.1.0.0
github:              "githubuser/HW4"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/HW4#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
  - -eventlog
  - -O2
  - -Wall
  - -Werror
  dependencies:
  - deepseq
  - parallel
  - transformers
  - microlens
  - random
  - comonad
  - directory
  - filepath

executables:
  HW4-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -eventlog
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N6
    - -Wall
    - -Werror
    dependencies:
    - HW4

tests:
  HW4-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N6
    - -Wall
    - -Werror
    dependencies:
    - HW4
    - hedgehog
    - hspec
    - tasty
    - tasty-hedgehog
    - tasty-hspec
    - transformers

benchmarks:
  criterion-benchmarks:
    main: Main.hs
    source-dirs: bench
    ghc-options:
    - -eventlog
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N6
    - -Wall
    - -Werror
    dependencies:
      - HW4
      - deepseq
      - criterion