name:                HW1
version:             0.1.0.0
github:              "githubuser/hw1-alexanderlvarfolomeev"
license:             BSD3
author:              "Alexander Varfolomeev"
maintainer:          "vas.aleks.v@gmail.com"
copyright:           "2020 Alexander Varfolomeev"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/HW1#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  HW1-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HW1

tests:
  HW1-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hedgehog
    - hspec
    - tasty
    - tasty-hedgehog
    - tasty-hspec
    - HW1
